README.md, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
Note that there’s an ambiguity in the spec about whether pronouns refer to the last *assigned* variable or the last *mentioned* variable. The text says “Pronouns refer to the last named variable determined by parsing order.”   Satriani, the reference implementation, only updates on assignment, so I’ve amended my implementation to behave the same way. (See discussion in https://github.com/RockstarLang/rockstar/issues/198)
  To align to Satriani, I removed the following implementation code   from my original implementation
  
```
  @Override
public void enterExpression(Rockstar.ExpressionContext ctx) {
// Pronouns refer to the last named variable determined by parsing order.
Rockstar.VariableContext variable = ctx.variable();
trackVariable(variable);
}
```
And the following tests 
``` …
```
=> Add support for pronouns

README.md, bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/ParseHelper.java
The spec says:
> Increment and Decrement
Increment and decrement are supported by the Build {variable} up and Knock {variable} down statements. Adding more than one up or down in the statement will increment or decrement the same amount of times as you have ups or downs in the statement. There may be a comma between each up and down.
> * Build my world up will increment the value stored in my world by 1.
> * Knock the walls down will decrement the value stored in the walls by 1
> * Knock the walls down, down will decrement the value stored in the walls by 2
All of this is now working. :)
=> Add support for increment and decrement

bon-jova-rockstar-implementation/src/main/java/org/example/Assignment.java, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/main/java/org/example/Constant.java, bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java, bon-jova-rockstar-implementation/src/main/java/org/example/Literal.java, bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java, bon-jova-rockstar-implementation/src/main/java/org/example/grammar/PoeticNumberLiteral.java, bon-jova-rockstar-implementation/src/test/java/org/example/AssignmentTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ConstantTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/LiteralTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/VariableTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/grammar/PoeticNumberLiteralTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/CapturingListener.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/ParseHelper.java
The spec says   
> Number - Numbers in Rockstar are double-precision floating point numbers, stored according to the IEEE 754 standard.
I had to look it up, but https://stackoverflow.com/questions/40300041/is-there-any-ieee-754-standard-implementations-for-java-floating-point-primitive suggests that a java double should meet this nicely. 
Eliminating integer from the parsing logic simplifies the code nicely, but introduces an extra requirement; when printing round numbers, they should be printed as an integer, with no trailing “.0”. 
The `DecimalFormat` class is able to do that nicely, but we need to know if we’re dealing with a number to invoke it. That’s slightly more complex, especially since `ResultHandle` does not expose its type information. I had to do an ugly hack to get at it. …
=> Use double for all numbers (plus refactoring)

bon-jova-rockstar-implementation/src/main/antlr4/rock/RockstarLexer.g4, bon-jova-rockstar-implementation/src/test/java/org/example/LiteralTest.java
The grammar couldn't parse negative numbers.
=> Support for negative number literals

bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
Resolves #16 
I also included trailing whitespace in the tests, and that seems to be tolerated without grammar changes.
=> Allow whitespace at the beginning of statements

README.md, bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/java/org/example/Assignment.java, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/main/java/org/example/Checker.java, bon-jova-rockstar-implementation/src/main/java/org/example/Condition.java, bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java, bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ConditionTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/CapturingListener.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/ParseHelper.java
From the spec:
> Conditionals
> Conditional expressions start with the If keyword, followed by an expression. If the expression evaluates to true, then the subsequent code block is executed. Optionally, an Else block can be written after an If block. The code block following the Else keyword would be executed if the If expression evaluated to false.
For the purpose of conditional expressions, 0, mysterious, null, false, and the empty string all evaluate to false, and everything else to true.
In order to meaningfully implement conditionals, I also had to implement comparisons. Doing comparison operators in bytecode was a bit harder than I expected. I drew inspiration from https://stackoverflow.com/questions/60137736/implementing-comparison-operators-in-bytecode-using-asm and ended up …
=> Add support for conditionals and comparisons

README.md, bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/antlr4/rock/RockstarLexer.g4, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
> ### Loops
> Similar to the If statement, a loop is denoted by the While or Until keyword, which will cause the subsequent code block to be executed repeatedly whilst the expression is satisfied:
> ```
> Tommy was a dancer
> While Tommy ain't nothing,
> Knock Tommy down
> ```
> That’ll initialize Tommy with the value 16 (using the poetic number literal syntax) and then loop, decrementing Tommy by 1 each time until Tommy equals zero (i.e ain't nothing returns false).
- Pending proper block support, only the first line in the loop is included in the execution. 
- Pending block support, `break` and `continue` are not supported. 
- A comparison like 'ain't nothing' is not possible yet, so it has to be 'ain't 0'
=> Add support for while and until loops

README.md, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/main/java/org/example/Constant.java, bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java, bon-jova-rockstar-implementation/src/main/java/org/example/Literal.java, bon-jova-rockstar-implementation/src/main/java/org/example/Nothing.java, bon-jova-rockstar-implementation/src/test/java/org/example/AssignmentTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ConstantTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java
The spec says 
> Mysterious - the value of any variable that hasn’t been assigned a value, denoted by the keyword mysterious
> Null - the null type. Evaluates as equal to zero and equal to false. The keywords nothing, nowhere, nobody, and gone are defined as aliases for null
> <Mysterious> <op> Mysterious => Equal.
> <Non-Mysterious> <op> Mysterious => Non equal.
> String <op> Null => Non equal.
> Number <op> Boolean => Convert number to boolean by “truthiness”.
> Number <op> Null => Convert null to 0.
> Boolean <op> Null => Convert null to false.
A naive implementation in byte code would be to treat rockstar `null` as Java `null`, but rockstar null has quite different semantics to Java null. The mysterious value is closer in behaviour to Java `null`. I've created a marker class for …
=> Improved support for mysterious and nothing, including comparisons

bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java, bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java
We format round numbers without the decimal point when doing a straight `say`, but not if they're concatenated with a string. This PR fixes that; it creates a bit of duplicated Java code and a bit of redundant bytecode, but that can be tidied later.
=> Format numbers correctly, even when concatenating to strings

bon-jova-rockstar-implementation/src/main/java/org/example/Assignment.java, bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java, bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java, bon-jova-rockstar-implementation/src/test/java/org/example/AssignmentTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/VariableTest.java
Allows variables to be initialised on assignment, when the other side is an operation. To implement this, I changed to storing type information with the variable object (which is probably a logical place for it).
=> Support for variable initialisation with operation expressions

bon-jova-app/src/test/java/HelloWorldTest.java, bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/BonJovaQuarkusExtensionTest.java, bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/RockstarCompilationProviderTest.java
Resolves #41 
I realised that the thing which is creating the problematic classes is the RockstarCompilationProviderTest, which specifies target/classes as its output directory.
However, switching that to a test output directory exposed a bug in BonJovaQuarkusExtensionTest. It relied on RockstarCompilationProviderTest running first (and leaving output in /test/classes) to pass. I was able to fix that by putting the .rock files into the Shrinkwrap archive, which is good, since that’s a stronger and better test anyway. Sadly, I couldn’t find a way to change the output directory in the Shrinkwrap archive, which meant the compiled rock classes ended up in … `test/classes`. In the end I gave up and put cleanup code in the BonJovaQuarkusExtensionTest.
=> Avoid including compiled rock files in the extension binaries

jitpack.yml
add jitpack.yml that will build with java 21.
allows me to run the compiler from anywhere `jbang --repos jitpack,central -m org.example.RockFileCompiler com.github.maxandersen.bon-jova-rockstar-implementation:bon-jova-rockstar-implementation:jitpack-9cace8e1a2-1`
if this gets committed it would be
`jbang --repos jitpack,central -m org.example.RockFileCompiler com.github.holly-cummins.bon-jova-rockstar-implementation:bon-jova-rockstar-implementation:main-SNAPSHOT`
that can be shortened greatly if you add main method in manifest and/or add a jbang-catalog :)
=> enable jitpack build

bon-jova-quarkus-extension/deployment/src/main/java/org/example/bon/jova/quarkus/extension/deployment/BonJovaQuarkusExtensionProcessor.java, bon-jova-quarkus-extension/deployment/src/main/resources/dev-ui/qwc-bon-jova-rockstar-endpoints.js, bon-jova-quarkus-extension/pom.xml, bon-jova-quarkus-extension/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Our extension now has a 'Rockstar Endpoints' menu option in the Dev UI! It leads to a static page that has the info on the available endpoints. And: it updates when you add a new .rock file! 🤩 
I haven't spent ANY time on the frontend yet (and it shows!), I'll try to work on that tomorrow. Oh, and we probably need a more sophisticated rock score than just the length of the program. 🤦 
By the way, I changed the extension description to:
> Shot through the heart and you're to blame! Run your Rockstar programs with Quarkus! 🎵
...because it's a LOT more rock 'n roll than what we had before. And as an added bonus I can sing this description live on stage. 😄 
(this PR closes #13 & #14)
=> Add menu option 'Rockstar Endpoints' that leads to a full page

bon-jova-app/src/main/rockstar/fizzbuzz.rock, bon-jova-quarkus-extension/integration-tests/src/test/resources-filtered/projects/simple-app/src/test/java/SimpleHelloWorldTest.java, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
I had two related-but-different problems where after using an `if` or a `while`, the scope would stay one level deeper than it should have. The problem didn't show up for test programs, but did show up in FizzBuzz. I've fixed them now, which is generally useful, and most importantly means ... 
(I haven't enabled the FizzBuzz integration test in this PR, because of #50.)
=> Correct scope nesting for loops and ifs

bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java
Obviously, #50  should Never Happen, and hopefully the code is now fixed so it doesn't. However, it would be useful to get better diagnostics when it does, so I've put in a little failsafe check. It won't catch the case where state leaks between classes of the same name, but I think such errors wouldn't actually affect the bytecode.
Initial PR designed to exercise failure path gives
```
Error:  shouldSetValueBasedOnStdIn  Time elapsed: 0.006 s  <<< ERROR!
java.lang.RuntimeException: Internal error: Attempting to use a field on class rock14973921548021469241 from com/InputRock
at org.example.InputTest.execute(InputTest.java:76)
at org.example.InputTest.shouldSetValueBasedOnStdIn(InputTest.java:44)
```
=> Trial run: give more informative error message when state leaks

bon-jova-app/src/main/rockstar/the_answer_to_life_the_universe_and_everything.rock, bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/antlr4/rock/RockstarLexer.g4, bon-jova-rockstar-implementation/src/main/java/org/example/Array.java, bon-jova-rockstar-implementation/src/main/java/org/example/Assignment.java, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java, bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java, bon-jova-rockstar-implementation/src/test/java/org/example/ArrayTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/CapturingListener.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/ParseHelper.java
This PR implements very basic array support; there is no `roll` support or support for non-numeric keys, or support for advanced features like poetic literals. However, programs like the following now work:
```
rock arr
rock 1 into arr
rock 5 into arr
rock 8 into arr
fred is 1
jane is nothing
say arr at 1 + 1
say arr at jane
say arr at fred
```
=> Basic array support

README.md, bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/antlr4/rock/RockstarLexer.g4, bon-jova-rockstar-implementation/src/main/java/org/example/Array.java, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/main/java/org/example/StringSplit.java, bon-jova-rockstar-implementation/src/test/java/StringSplitTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/VariableTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/CapturingListener.java, bon-jova-rockstar-implementation/src/test/java/org/example/util/ParseHelper.java
I've added support for splitting strings, but not for writing back the split string to the original variable. 
It turns out `Arrays.toList()` does not use the same `ArrayList` as the rest of the Java language, so I've had to switch from using `ArrayList` methods in `Array` to using the interface methods. 
I also noticed that `your lies` cannot be used as a variable because the `lies` is detected as a boolean, so I've added a disabled test for that.
=> Add support for splitting strings

README.md, bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/antlr4/rock/RockstarLexer.g4, bon-jova-rockstar-implementation/src/main/java/org/example/Array.java, bon-jova-rockstar-implementation/src/main/java/org/example/Assignment.java, bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java, bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/VariableTest.java
Resolves #18; both test cases in that issue now pass. There is some more work to do around the edges of dynamic type support, such as allowing strings to be split in place, and full casting support, but the basics are in place. 
This PR also provides basic support for casting strings to doubles, using a normal base 10 conversion.
=> Dynamic type support and basic casting implementation

bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/BonJovaQuarkusExtensionTest.java, bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/java/org/example/Array.java, bon-jova-rockstar-implementation/src/main/java/org/example/RockFileCompiler.java, bon-jova-rockstar-implementation/src/main/java/org/example/RockstarArray.java, bon-jova-rockstar-implementation/src/main/java/org/example/StringSplit.java, bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java, bon-jova-rockstar-implementation/src/test/java/StringSplitTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/ArrayTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/RockstarArrayTest.java
I discovered, when I tried to use it in a real program, that my implementation of non-numeric keys was brittle; because it relied on a shadow second variable, accessed by naming convention, it would break when arrays were used in assignments, and also when strings were split into arrays. 
I've bitten the bullet and switched to providing an external class which encapsulates the logic. This makes the programs a bit less free-standing, but a *lot* shorter and cleaner. It also would have saved me a bunch of bytecode generation, had I done this the first time round.
=> Improve robustness of non numeric array keys

bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/main/java/org/example/grammar/PoeticNumberLiteral.java, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
The spec says 
> A poetic number literal begins with a variable name, followed by the keyword is, or the aliases are, was or were. As long as the next symbol is not a Literal Word, the rest of the line is treated as a decimal number in which the values of consecutive digits are given by the lengths of the subsequent barewords, up until the end of the line.
I've now fixed the implementation. It's the risky sort of fix where something else might regress, so be aware. Hopefully the tests caught everything! It was lucky the second word in your example was 'low', @hannotify, since my fix initially broke toleration for that word ... but your example caught it (phew!).
=> Tolerate constants in poetic number literals, except as the first word

bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java
I noticed when testing 1brc that we have a problem reading arrays, sometimes, because of interference with the support for dynamically changing the type of a variable; there's a difference between compatible type changes, when we want to keep the field, and incompatible changes, when we want to throw it out. 
I've put in a fix, but we should also add more tests and maybe something overall more robust.
=> Do not discard existing fields when we narrow the type of a variable

bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4, bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java, bon-jova-rockstar-implementation/src/test/java/org/example/integration/IntegrationTests.java
They should be counted as part of the function declaration. 
This fixes #104, but I don't entirely understand the mechanism. What's extra confusing is that the same code fails, when run as part of the bytecode generator unit tests - why?!
=> Don't allow return statements in statement lists

pom.xml, quarkus-bon-jova-rockstar/compiler/pom.xml
Resolves this output on app start, when running with Quarkus 3.7.1:
```
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.13.0
ANTLR Runtime version 4.10.1 used for parser compilation does not match the current runtime version 4.13.0
ANTLR Tool version 4.10.1 used for code generation does not match the current runtime version 4.13.0
ANTLR Runtime version 4.10.1 used for parser compilation does not match the current runtime version 4.13.0
```
Quarkus ships with Antlr, and Antlr is annoyingly fussy about cross-version compatibility. We could pull in the Quarkus bom to ensure we were aligned, but that would still ensure alignment for the version of Quarkus the extension was built with.
=> Align Antlr version with one used by Quarkus

quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Array.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Assignment.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratingListener.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Constant.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Expression.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Literal.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Nothing.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/RockFileCompiler.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Rounding.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/ValueHolder.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Variable.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/support/Nothing.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/AssignmentTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratorTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/ConstantTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/ExpressionTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/InputTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/LiteralTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/VariableTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/support/NothingTest.java, quarkus-bon-jova-rockstar/docs/modules/ROOT/pages/includes/attributes.adoc, quarkus-bon-jova-rockstar/docs/templates/includes/attributes.adoc
To distinguish between nothing and mysterious, we need a type. I've added a Nothing type, with behaviours. This allows us to enable several of the mysterious-related tests. 
There's still lots of todos in the code about coercion, and lots of messiness that could be tidied up, but I think this is a step in the right direction. 
Resolves #98.
=> Improved support for nothing and mysterious

quarkus-bon-jova-rockstar/lyrics/src/test/java/io/quarkiverse/bonjova/lyrics/LyricsReaderTest.java
See #158. I think this may be a functional concurrency issue, not just a test issue, but it does not seem to affect our laptops, so it's hard to reproduce and fix.
=> Disable failing test pending fix

quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Array.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Assignment.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Block.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratingListener.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Cast.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Condition.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Constant.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Expression.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Input.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Literal.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Parameter.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Rounding.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/StringSplit.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/ValueHolder.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/Variable.java, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/VariableScope.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/ArrayTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/AssignmentTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratorTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/CastTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/ConstantTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/ExpressionTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/InputTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/LiteralTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/ParameterTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/RoundingTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/StringSplitTest.java
This resolves #99, and partially resolves #112.
There's still some problems in the generated bytecode, caused by use of static variables where we should use method-scoped variables (assignable result handles, maybe?), but the external behaviour is now correct.
=> Scope variables with access to parent scope, and introduce parameter behaviour for function calls

quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratorTest.java
Reproduces #154, and this also adds a useful extra check to the tests, to make sure there's no stderr. Interestingly, #146 doesn't make it fail, so those errors must be coming earlier in the lifecycle.
=> Reproducer for #154

quarkus-bon-jova-rockstar/compiler/src/main/antlr4/rock/Rockstar.g4, quarkus-bon-jova-rockstar/compiler/src/main/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratingListener.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratorTest.java, quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/integration/IntegrationTests.java, quarkus-bon-jova-rockstar/compiler/src/test/resources/mandelbrot.rock
Resolves #154. 
The behaviour is still not identical to Satriani; now, a blank line before the 'give' will cause bad behaviour in Satriani, and work in Bon Jova. Similarly, Satriani *requires* a blank line before the 'give' in a loop, in Bon Jova does not. 
However, the current behaviour seems consistent with the spec and unlikely to cause problems (the old requirement for a blank line meant the mandelbrot code couldn't be copy-pasted from the Rockstar samples, for example).
=> Allow return statements to (effectively) terminate statement lists

quarkus-bon-jova-rockstar/compiler/pom.xml
Resolves #146 
The quarkiverse-parent pom a logmanager property in its surefire configuration, so unless we switch the compiler to have a totally different parent, it will need that log manager on its test classpath.
=> Add explicit dependency on logger used in grandparent's surefire config

bon-jova-app/pom.xml, quarkus-bon-jova-rockstar/deployment/src/main/resources/dev-ui/qwc-bon-jova-rockstar-endpoints.js, quarkus-bon-jova-rockstar/deployment/src/test/java/io/quarkiverse/bonjova/quarkus/extension/deployment/RockstarCompilationProviderTest.java, quarkus-bon-jova-rockstar/pom.xml
Following instructions for code changes in https://github.com/quarkusio/quarkus/pull/38848.
Marking as draft, since at the moment this update makes the endpoint list disappear.
=> Update to Quarkus 3.9.1 to get new code block in dev ui
