quarkiverse/quarkus-bon-jova-rockstar

bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4
bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java
bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/RockFileCompilerTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/util/FileLauncher.java

This was missing, so I've added it in. 
I've also improved tolerance for whitespace in statements, although looking at the [99 beers sample](https://codewithrockstar.com/online?source=/rockstar/examples/99_beers.rock) the whitespace is expected to be interpreted as a leading part of the poetic string literal, not ignored. So we may need to revisit the whitespace again, but at least now the whitespace doesn't cause parse errors.

Support for string concatenation

---

bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4
bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java
bon-jova-rockstar-implementation/src/test/java/org/example/AssignmentTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/VariableTest.java

Include leading whitespace in poetic string literals, tolerate whitepace elsewhere

Improved whitespace parsing

---

README.md
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java

Comments turned out to already be working, but of course we want a test to make sure they keep working.

Test for comment support

---

bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/BonJovaQuarkusExtensionTest.java
bon-jova-quarkus-extension/deployment/src/test/resources/hello_hanno_hello_holly.rock
bon-jova-quarkus-extension/runtime/src/main/java/org/example/bon/jova/quarkus/extension/runtime/RockstarResource.java

The Rockstar endpoint now supports the `arg` parameter, which expects one or more values bound to it. They will be passed to the `main` method of the compiled Rockstar program.

Read query params on rest endpoint and pipe to rockstar's stdin

---

README.md
bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/BonJovaQuarkusExtensionTest.java
bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/RockstarCompilationProviderTest.java
bon-jova-quarkus-extension/deployment/src/test/resources/hello_hanno_hello_holly.rock
bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java
bon-jova-rockstar-implementation/src/main/java/org/example/Input.java
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/InputTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/integration/IntegrationTests.java
bon-jova-rockstar-implementation/src/test/java/org/example/util/CapturingListener.java
bon-jova-rockstar-implementation/src/test/java/org/example/util/ParseHelper.java

In practice, this just means reading the arguments passed to the main method. 
I discovered when doing the tests for this that the extension test still isn't triggering compilation of its `.rock` files, so I had to update the compilation test with the extension test's test data – ick. I raised #47 to cover the issue.

Add support for reading from stdin

---

README.md
bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4
bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java
bon-jova-rockstar-implementation/src/main/java/org/example/Constant.java
bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java

This PR bundles together a few improvements:
- Correcting order of operations for functions, so that the parameters bind tightest to the function invocation
- Adding support for AND conjunctions (but not other logic operations)
- Improving handling of nothing in functions, so we have more type coercion and fewer validation errors

Improve handling of compound function invocations and null types

---

README.md
bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4
bon-jova-rockstar-implementation/src/main/java/org/example/Array.java
bon-jova-rockstar-implementation/src/main/java/org/example/StringSplit.java
bon-jova-rockstar-implementation/src/test/java/org/example/ArrayTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java

Further extension of the array support; allows programs like 
```
Let the array at 0 be "zero"
Let the array at 1 be "one"
Let the array at 255 be "big"
Shout the array at 0
Shout the array at 255
```

Allow writing to an array at a given index

---

bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4

I noticed a warning from antlr during 99 bottles of beer.

Add keyword to grammar to tidy warning

---

bon-jova-rockstar-implementation/src/main/java/org/example/Array.java
bon-jova-rockstar-implementation/src/main/java/org/example/Assignment.java
bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java
bon-jova-rockstar-implementation/src/main/java/org/example/Condition.java
bon-jova-rockstar-implementation/src/main/java/org/example/Constant.java
bon-jova-rockstar-implementation/src/main/java/org/example/Expression.java
bon-jova-rockstar-implementation/src/main/java/org/example/Input.java
bon-jova-rockstar-implementation/src/main/java/org/example/Literal.java
bon-jova-rockstar-implementation/src/main/java/org/example/RockstarArray.java
bon-jova-rockstar-implementation/src/main/java/org/example/Variable.java
bon-jova-rockstar-implementation/src/test/java/org/example/ArrayTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/AssignmentTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/ConstantTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/ExpressionTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/InputTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/LiteralTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/RockstarArrayTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/VariableTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/integration/IntegrationTests.java

This PR also includes functional fixes:
- Wholesale rewrite of the type model, to treat everything as an object. I wasn’t totally sure if this was the best thing, and it was a large and invasive change so I left some obsolete code and broken tests, and just disabled them.
- Arrays need to be re-initialised on push if they’d been set to null
- Arrays should tolerate get at indexes past the end of the array
- Input needs to increment its index in bytecode, not in the bytecode generation
- Null checks on a compareTo

Try and improve behaviour by going fully dynamic with types and never using primitives

---

bon-jova-quarkus-extension/runtime/src/main/resources/META-INF/quarkus-extension.yaml

See https://github.com/quarkusio/quarkus/issues/38530#issuecomment-1921481805

Mark extension as experimental

---

README.md
bon-jova-rockstar-implementation/src/main/antlr4/rock/Rockstar.g4
bon-jova-rockstar-implementation/src/main/java/org/example/BytecodeGeneratingListener.java
bon-jova-rockstar-implementation/src/main/java/org/example/Cast.java
bon-jova-rockstar-implementation/src/test/java/org/example/BytecodeGeneratorTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/CastTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/StringSplitTest.java
bon-jova-rockstar-implementation/src/test/java/org/example/util/CapturingListener.java
bon-jova-rockstar-implementation/src/test/java/org/example/util/ParseHelper.java

I couldn't get the unit tests to work for this, but the higher level tests worked. 
There's one higher-level case where trying to cast a literal directly gives a verify error (why?!) but I haven't dug into it; we should also come back to that and see what's going on.

Support casting numbers to a character/string

---

bon-jova-quarkus-extension/deployment/pom.xml
bon-jova-quarkus-extension/deployment/src/main/java/org/example/bon/jova/quarkus/extension/deployment/BonJovaQuarkusExtensionProcessor.java
bon-jova-quarkus-extension/deployment/src/main/java/org/example/bon/jova/quarkus/extension/deployment/lyrics/LyricsRatingCalculator.java
bon-jova-quarkus-extension/deployment/src/main/java/org/example/bon/jova/quarkus/extension/deployment/rockscore/RockScoreCalculator.java
bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/lyrics/LyricsRatingCalculatorTest.java
bon-jova-quarkus-extension/deployment/src/test/java/org/example/bon/jova/quarkus/extension/deployment/rockscore/RockScoreCalculatorTest.java
bon-jova-quarkus-extension/lyrics/pom.xml
bon-jova-quarkus-extension/lyrics/src/main/java/org/example/bon/jova/quarkus/extension/lyrics/LyricsFileUtil.java
bon-jova-quarkus-extension/lyrics/src/main/java/org/example/bon/jova/quarkus/extension/lyrics/LyricsReader.java
bon-jova-quarkus-extension/lyrics/src/main/java/org/example/bon/jova/quarkus/extension/lyrics/LyricsSanitizer.java
bon-jova-quarkus-extension/lyrics/src/main/java/org/example/bon/jova/quarkus/extension/lyrics/RemoteLyricsReader.java
bon-jova-quarkus-extension/lyrics/src/main/java/org/example/bon/jova/quarkus/extension/lyrics/Song.java
bon-jova-quarkus-extension/lyrics/src/main/java/org/example/bon/jova/quarkus/extension/lyrics/WordCounter.java
bon-jova-quarkus-extension/lyrics/src/test/java/org/example/bon/jova/quarkus/extension/lyrics/LyricsReaderTest.java
bon-jova-quarkus-extension/lyrics/src/test/java/org/example/bon/jova/quarkus/extension/lyrics/WordCounterTest.java
bon-jova-quarkus-extension/pom.xml

The separate module worked wonders! 😄 
Closes #80.

Isolate lyrics feature in a separate module

---

bon-jova-app/pom.xml
quarkus-bon-jova-rockstar/docs/modules/ROOT/pages/includes/attributes.adoc

I had to make these changes to make `mvn install` work from the root dir. WDYT?

Update quarkus-bon-jova dependency from app to 0.4.0

---

.github/project.yml

Doing a release, partly to get the updated antlr version into a release, but also to
- exercise the process and make sure it's trouble free now, after a torrd first release
- see if the extension catalog will pick up the new release

Second release

---

bon-jova-app/pom.xml

Resolves #49. I copied the config from a pom created with `quarkus create`

Tidy maven compiler plugin config

---

quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/integration/IntegrationTests.java
quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/util/FileLauncher.java

… and improve integration test test names

Give compiled tests meaningful names, 

---

quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratorTest.java

Add reproducer for #159

---

quarkus-bon-jova-rockstar/compiler/src/test/java/io/quarkiverse/bonjova/compiler/BytecodeGeneratorTest.java

Reproducer for problem where arrays need to be initialised before using them in a loop

---

.github/workflows/build.yml

This should also help confirm that current CI failures are unrelated to code changes.

Allow builds to be triggered through UI

---

quarkus-bon-jova-rockstar/compiler/src/test/resources/mandelbrot-boring.rock

Not boring enough, but more boring than before

Make boring-mandelbrot more boring
